services:
  searxng:
    image: searxng/searxng:latest
    restart: always
    volumes:
      - ./searxng:/etc/searxng:rw
  varnish: 
    image: allfunc/varnish-alpine
    restart: always
    depends_on:
      - searxng
    environment:
      - VARNISH_BACKEND_ADDRESS=searxng
      - VARNISH_BACKEND_PORT=8080
    ports:
      - 58080:80
